-- Création de la table AdminSystem
CREATE TABLE AdminSystem (
    idAdmin NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomAdmin VARCHAR2(255),
    prenomAdmin VARCHAR2(255),
    emailAdmin VARCHAR2(255),
    motDePasseAdmin VARCHAR2(255)
);

-- Création de la table Filiere
CREATE TABLE Filiere (
    idFiliere NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomFiliere VARCHAR2(50), -- Enum stocké comme String
    descriptionFiliere VARCHAR2(500),
    dateCreation DATE
);

-- Création de la table ChefFiliere
CREATE TABLE ChefFiliere (
    numCf NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomCf VARCHAR2(255),
    prenomCf VARCHAR2(255),
    emailCf VARCHAR2(255),
    motDePasseCf VARCHAR2(255),
    dateDembauche DATE,
    id_filiere NUMBER,
    CONSTRAINT FK_ChefFiliere_Filiere FOREIGN KEY (id_filiere) REFERENCES Filiere (idFiliere)
);

-- Création de la table Entreprise
CREATE TABLE Entreprise (
    siretEntreprise NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raisonSocialeEntreprise VARCHAR2(255),
    formeJuridique VARCHAR2(255),
    adresseEntreprise VARCHAR2(255),
    villeEntreprise VARCHAR2(255),
    codePostalEntreprise VARCHAR2(10),
    telephoneEntreprise VARCHAR2(15),
    faxEntreprise VARCHAR2(15),
    contactEntreprise VARCHAR2(255),
    telContact VARCHAR2(15)
);

-- Création de la table Etudiant
CREATE TABLE Etudiant (
    numeroEtudiant NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomEtudiant VARCHAR2(255),
    prenomEtudiant VARCHAR2(255),
    adresseEtudiant VARCHAR2(255),
    dateDeNaissanceEtudiant DATE,
    telephoneEtudiant VARCHAR2(15),
    statusRechercheEtudiant VARCHAR2(255),
    promotionEtudiant VARCHAR2(50),
    filiereEtudiant VARCHAR2(255),
    emailEtudiant VARCHAR2(255),
    motDePasseEtudiant VARCHAR2(255),
    id_filiere NUMBER,
    CONSTRAINT FK_Etudiant_Filiere FOREIGN KEY (id_filiere) REFERENCES Filiere (idFiliere)
);

-- Création de la table OffreStage (relation avec Entreprise non incluse dans votre code mais mentionnée)
CREATE TABLE OffreStage (
    idOffre NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titreOffre VARCHAR2(255),
    descriptionOffre CLOB,
    dateDebut DATE,
    dateFin DATE,
    siretEntreprise NUMBER,
    CONSTRAINT FK_OffreStage_Entreprise FOREIGN KEY (siretEntreprise) REFERENCES Entreprise (siretEntreprise)
);

-- Création de la table GestionnaireEntreprise (relation avec Entreprise non incluse dans votre code mais mentionnée)
CREATE TABLE GestionnaireEntreprise (
    idGestionnaire NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomGestionnaire VARCHAR2(255),
    prenomGestionnaire VARCHAR2(255),
    emailGestionnaire VARCHAR2(255),
    motDePasseGestionnaire VARCHAR2(255),
    siretEntreprise NUMBER,
    CONSTRAINT FK_GestionnaireEntreprise_Entreprise FOREIGN KEY (siretEntreprise) REFERENCES Entreprise (siretEntreprise)
);
